language: swift
osx_image: xcode11.1
xcode_workspace: Paradigms.xcworkspace
xcode_scheme: Paradigms
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 11
before_install:
    - gem install bundler -v 2.0.1
